services:
  - type: web
    name: legal-summarizer
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr ffmpeg
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata
